### ISSUE TITLE
Check for correct export in QEMU example

### ISSUE THREAD

**Issue by alwin-joshy** [au-ts/sddf#100]
https://github.com/au-ts/sddf/blob/693f1b226aabd486b0b82e0a014d892f9f287f35/drivers/clock/arm/timer.c#L6-L8

Based on https://developer.arm.com/documentation/ddi0595/2021-06/AArch64-Registers/CNTHCTL-EL2--Counter-timer-Hypervisor-Control-register?lang=en#fieldset_0-10_10, both EXPORT_PTMR_USER and EXPORT_PCNT_USER should be enabled.

**Comment by Ivan-Velickovic** [comment]
Fixed in https://github.com/au-ts/sddf/pull/93.
