### ISSUE TITLE
Serial subsystem instability

### ISSUE THREAD

**Issue by JE-Archer** [au-ts/sDDF#42]
Two observed issues with the serial subsystem on an OdroidC4:

1. When using the serial subsystem for a REPL, after typing for a while, or after pasting into the terminal, I/O becomes desynced. When typing, e.g. "abc", after pressing "a", nothing appears, then upon typing "b", the "a" appears, and upon typing "c", the "b" appears, and so on.

2. When pushing large amounts of data through the serial output, the driver and multiplexer PDs crashed after a number of seconds.

**Comment by Ivan-Velickovic** [comment]
1. has been fixed, 2. is being looked into.
