### ISSUE TITLE
Re-design serial sub-system

### ISSUE THREAD

**Issue by Ivan-Velickovic** [au-ts/sddf#53]
The serial sub-system was created initially based on the network sub-system design and currently follows that closely.

We have now revisited the design of the serial sub-system and are going to now revamp the design for character by character serial devices/drivers and leave the design for DMA serial for later.

The new design is still being discussed, but essentially the 'DMA data region' that appears in networking will be gone and we will instead have serial data stored inside the shared queue regions. The drivers will be simplified by leaving all processing/cooking to the virtualisers.

In addition, there are various minor issues in the serial sub-system code that should be cleaned up. The serial sub-system is still a work-in-progress and so there are larger design decisions to discuss as well. Some of these issues already have PRs opened to deal with it.

- [x] no busy waiting in serial server example
- [x] get rid of cookie in shared ring buffer.
- [x] rename ring_* to serial_ring_*
- [ ] Document RAW_MODE, ECHO_MODE, LINE_MODE etc
    - [x] Secondly, I do not think the driver should be doing this kind of processing.
~~- [ ] We really need some systematic logging~~
- [x] Try not comment out assert and puthex64
- [x] Use `sddf_dprintf` instead of `microkit_dbg_puts` for easier printing
~~- [ ] Fixup serial example Makefile to call into queue Makefile~~ obsolete now that the queue is header-only
- [x] All the state stuff needs to be cleaned up in the drivers and virtualisers, it is hard to decipher what is in what state when.
- [x] virtualisers dequeue only one used entry at a time
- [x] use offsets instead of raw addresses
- [x] follow a similar API to network with `serial_queue_init` not needing and `buffer_init` flag or anything and instead relying on global initialization
- [ ] sort out https://github.com/au-ts/sddf/issues/66 at the same time
- [x] fix use of `atoi` in virtualiser, we should be able to have more than 10 clients. If we do not support more than 10 clients, we should remove the call to `atoi`.

**Comment by Courtney3141** [comment]
Add a debug print statement on the rx virt when a switch char has been received.

**Comment by Ivan-Velickovic** [comment]
Done in https://github.com/au-ts/sddf/pull/99.
